services:
  tailscale-3x-ui:
    image: ghcr.io/modimobeikete/tailscale-3x-ui:main
    container_name: tailscale-3x-ui
    hostname: yourhostname
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
      - /vol1/1000/docker/tailscale/state:/var/lib/tailscale # 映射状态目录
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      X_UI_ENABLE_FAIL2BAN: "true"
      TAILSCALE_AUTHKEY: "${TAILSCALE_AUTHKEY}"
    tty: true
    network_mode: host
    restart: unless-stopped
